version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: basedatos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: