version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basedatos
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: